Revert "bmks: dont use && before exits. we wanna exit regardless"
This reverts commit 377ecea50ec0f2c0560e8768ca1ed298ca81a6b3.

diff --git a/sh/bmks b/sh/bmks
--- a/sh/bmks
+++ b/sh/bmks
@@ -11,7 +11,7 @@ usage() {
 }
 
 add() { 
-	[ -z "${url}" ] && printf "Error: url must be provided\n"; exit 1
+	[ -z "${url}" ] && printf "Error: url must be provided\n" && exit 1
 	printf "Description: "
 	read -r description
 	if [ -z "${description}" ]; then
@@ -26,8 +26,8 @@ list() {
 }
 
 go_to() {
-	[ ! -s "${bookmarks}" ] && printf "No bookmarks found. please add one"; exit 1
-	[ -z "${BROWSER}" ] && printf 'BROWSER var not set\n'; exit 1
+	[ ! -s "${bookmarks}" ] && printf "No bookmarks found. please add one" && exit 1
+	[ -z "${BROWSER}" ] &&  printf 'BROWSER var not set\n' && exit 1
 	SELECTION="$(sort "${bookmarks}" | dmenu -c -i -l 10 | awk '{print $(NF)}')"
 	if [ -z "${SELECTION}" ]; then
 		exit 1
